version: 2.1

orbs:
  android: circleci/android@2.3.0

jobs:
  build:
    executor: android/android

    steps:
      - checkout
      - run:
          name: Set Java 17
          command: |
            java -version
            echo 'export JAVA_HOME=$(/usr/libexec/java_home)' >> $BASH_ENV
            source $BASH_ENV
            echo $JAVA_HOME
      - run:
          command: ./gradlew build