version: 2.1

workflows:
  build:
    jobs:
      - build

jobs:
  build:
    executor:
      name: android/android
    docker:
      - image: cimg/android:2024.01-node
    steps:
      - checkout
      - run:
          name: Set Java 17 and Check Version
          command: |
            java -version
            export JAVA_HOME=/opt/java/openjdk
            echo "JAVA_HOME is set to: $JAVA_HOME"
      - run:
          command: ./gradlew build